// <auto-generated />
using ContainerDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContainerDB.Migrations
{
    [DbContext(typeof(ContainerDBContext))]
    [Migration("20181118080705_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ContainerDB.Models.LocationsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContainerID");

                    b.Property<string>("Tauranga");

                    b.Property<string>("Lyttleton");

                    b.Property<string>("Timaru");

                    b.Property<int>("Otago");

                    b.Property<string>("Kiwirail");

                    b.Property<string>("PortConnect");

                    b.HasKey("Id");

                    b.ToTable("LocationsItem");
                });
#pragma warning restore 612, 618
        }
    }
}
