// <auto-generated />
using ContainerDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContainerDB.Migrations
{
    [DbContext(typeof(ContainerDBContext))]
    partial class ContainerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ContainerDB.Models.LocationsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContainerID");

                    b.Property<string>("Tauranga");

                    b.Property<string>("Lyttleton");

                    b.Property<string>("Timaru");

                    b.Property<string>("Otago");

                    b.Property<string>("Kiwirail");

                    b.Property<string>("PortConnect");

                    b.HasKey("Id");

                    b.ToTable("LocationsItem");
                });

            modelBuilder.Entity("ContainerDB.Models.ContainerItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ContainerID");

                b.Property<string>("shipco");

                b.Property<string>("size");

                b.Property<int>("grade");

                b.Property<string>("location");

                b.Property<bool>("full");

                b.Property<string>("status");

                b.Property<string>("time");

                b.Property<string>("type");

                b.HasKey("Id");

                b.ToTable("ContainerItem");
            });

            modelBuilder.Entity("ContainerDB.Models.UserItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("username");

                b.Property<string>("password");

                b.HasKey("Id");

                b.ToTable("UserItem");
            });
#pragma warning restore 612, 618
        }
    }
}
